all: .1 .2 .3 .4 .5 .6 .7 .8 .9 .10 .11 .12

.1: 1.cpp
g++ -Werror -Wextra -Wall -std=c++11 1.cpp -o 1

.2: 2.cpp
g++ -Werror -Wextra -Wall -std=c++11 2.cpp -o 2

.3: 3.cpp
g++ -Werror -Wextra -Wall -std=c++11 3.cpp -o 3

.4: 4.cpp
g++ -Werror -Wextra -Wall -std=c++11 4.cpp -o 4

.5: 5.cpp
g++ -Werror -Wextra -Wall -std=c++11 5.cpp -o 5

.6: 6.cpp
g++ -Werror -Wextra -Wall -std=c++11 6.cpp -o 6

.7: 7.cpp
g++ -Werror -Wextra -Wall -std=c++11 7.cpp -o 7

.8: 8.cpp
g++ -Werror -Wextra -Wall -std=c++11 8.cpp -o 8

.9: 9.cpp
g++ -Werror -Wextra -Wall -std=c++11 9.cpp -o 9

.10: 10.cpp
g++ -Werror -Wextra -Wall -std=c++11 10.cpp -o 10

.11: 11.cpp
g++ -Werror -Wextra -Wall -std=c++11 11.cpp -o 11

.12: 12.cpp
g++ -Werror -Wextra -Wall -std=c++11 12.cpp -o 12

clean: 
	rm -rf 1 2 3 4 5 6 7 8 9 10 11 12

rebuild: clean all

1: 1
	./1
2: 2
	./2
3: 3
	./3
4: 4
	./4
5: 5
	./5
6: 6
	./6